using PhraseFlow.Core.Placeholders;
using static PhraseFlow.App.Native.NativeMethods;

namespace PhraseFlow.App.Native;

/// <summary>Synthesizes keyboard input with <c>SendInput</c>.</summary>
internal static unsafe class InputInjector
{
    /// <summary>Marks input generated by PhraseFlow so the keyboard hook ignores it.</summary>
    public const nuint Signature = 0x50464C57;

    /// <summary>Marks user keystrokes that were held back during an expansion and are replayed afterwards.</summary>
    public const nuint ReplaySignature = 0x50465250;

    private const int ChunkSize = 400;

    public static INPUT Key(int vk, bool up, nuint signature = Signature)
    {
        var flags = up ? KEYEVENTF_KEYUP : 0u;
        if (VirtualKeys.IsExtended(vk))
        {
            flags |= KEYEVENTF_EXTENDEDKEY;
        }

        return new INPUT
        {
            type = INPUT_KEYBOARD,
            u = new InputUnion
            {
                ki = new KEYBDINPUT
                {
                    wVk = (ushort)vk,
                    wScan = (ushort)MapVirtualKeyW((uint)vk, MAPVK_VK_TO_VSC),
                    dwFlags = flags,
                    dwExtraInfo = signature,
                },
            },
        };
    }

    public static INPUT Unicode(char c, bool up, nuint signature = Signature) => new()
    {
        type = INPUT_KEYBOARD,
        u = new InputUnion
        {
            ki = new KEYBDINPUT
            {
                wVk = 0,
                wScan = c,
                dwFlags = KEYEVENTF_UNICODE | (up ? KEYEVENTF_KEYUP : 0u),
                dwExtraInfo = signature,
            },
        },
    };

    /// <summary>Sends the inputs in chunks and returns how many events Windows accepted.</summary>
    public static int Send(List<INPUT> inputs)
    {
        var sent = 0;
        for (var offset = 0; offset < inputs.Count; offset += ChunkSize)
        {
            var count = Math.Min(ChunkSize, inputs.Count - offset);
            var span = System.Runtime.InteropServices.CollectionsMarshal.AsSpan(inputs).Slice(offset, count);
            fixed (INPUT* pointer = span)
            {
                var accepted = (int)SendInput((uint)count, pointer, sizeof(INPUT));
                sent += accepted;
                if (accepted < count)
                {
                    break;
                }
            }
        }

        return sent;
    }

    public static void AddKeyPress(List<INPUT> inputs, int vk, int repeat = 1, nuint signature = Signature)
    {
        for (var i = 0; i < repeat; i++)
        {
            inputs.Add(Key(vk, up: false, signature));
            inputs.Add(Key(vk, up: true, signature));
        }
    }

    /// <summary>Adds the key events that type <paramref name="text"/>; new lines and tabs become Enter/Tab presses.</summary>
    public static void AddText(List<INPUT> inputs, string text, nuint signature = Signature)
    {
        for (var i = 0; i < text.Length; i++)
        {
            var c = text[i];
            switch (c)
            {
                case '\r':
                    if (i + 1 < text.Length && text[i + 1] == '\n')
                    {
                        continue;
                    }

                    AddKeyPress(inputs, VirtualKeys.Return, signature: signature);
                    break;
                case '\n':
                    AddKeyPress(inputs, VirtualKeys.Return, signature: signature);
                    break;
                case '\t':
                    AddKeyPress(inputs, VirtualKeys.Tab, signature: signature);
                    break;
                default:
                    inputs.Add(Unicode(c, up: false, signature));
                    inputs.Add(Unicode(c, up: true, signature));
                    break;
            }
        }
    }

    public static void TypeText(string text, int delayMs)
    {
        if (delayMs <= 0)
        {
            var inputs = new List<INPUT>(text.Length * 2);
            AddText(inputs, text);
            Send(inputs);
            return;
        }

        foreach (var element in EnumerateTextElements(text))
        {
            var inputs = new List<INPUT>(4);
            AddText(inputs, element);
            Send(inputs);
            Thread.Sleep(delayMs);
        }
    }

    public static void PressKey(int vk, int repeat = 1)
    {
        var inputs = new List<INPUT>(repeat * 2);
        AddKeyPress(inputs, vk, repeat);
        Send(inputs);
    }

    /// <summary>Presses a key chord such as Ctrl+Shift+S, <paramref name="repeat"/> times.</summary>
    public static void SendChord(KeyChord chord, int repeat, nint keyboardLayout)
    {
        var vk = chord.VirtualKey;
        var modifiers = chord.Modifiers;
        if (chord.Character is { } character)
        {
            var scan = VkKeyScanExW((ushort)character, keyboardLayout);
            if (scan == -1)
            {
                var text = new List<INPUT>();
                for (var i = 0; i < repeat; i++)
                {
                    AddText(text, character.ToString());
                }

                Send(text);
                return;
            }

            vk = scan & 0xFF;
            var shiftState = (scan >> 8) & 0xFF;
            if ((shiftState & 1) != 0)
            {
                modifiers |= KeyModifiers.Shift;
            }

            if ((shiftState & 2) != 0)
            {
                modifiers |= KeyModifiers.Ctrl;
            }

            if ((shiftState & 4) != 0)
            {
                modifiers |= KeyModifiers.Alt;
            }
        }

        var modifierKeys = new List<int>();
        if (modifiers.HasFlag(KeyModifiers.Ctrl))
        {
            modifierKeys.Add(VirtualKeys.LControl);
        }

        if (modifiers.HasFlag(KeyModifiers.Alt))
        {
            modifierKeys.Add(VirtualKeys.LMenu);
        }

        if (modifiers.HasFlag(KeyModifiers.Shift))
        {
            modifierKeys.Add(VirtualKeys.LShift);
        }

        if (modifiers.HasFlag(KeyModifiers.Win))
        {
            modifierKeys.Add(VirtualKeys.LWin);
        }

        var inputs = new List<INPUT>();
        for (var i = 0; i < repeat; i++)
        {
            foreach (var m in modifierKeys)
            {
                inputs.Add(Key(m, up: false));
            }

            inputs.Add(Key(vk, up: false));
            inputs.Add(Key(vk, up: true));
            for (var m = modifierKeys.Count - 1; m >= 0; m--)
            {
                inputs.Add(Key(modifierKeys[m], up: true));
            }
        }

        Send(inputs);
    }

    public static void Paste(Core.Models.PasteShortcut shortcut)
    {
        var inputs = new List<INPUT>(4);
        if (shortcut == Core.Models.PasteShortcut.ShiftInsert)
        {
            inputs.Add(Key(VirtualKeys.LShift, up: false));
            inputs.Add(Key(VirtualKeys.Insert, up: false));
            inputs.Add(Key(VirtualKeys.Insert, up: true));
            inputs.Add(Key(VirtualKeys.LShift, up: true));
        }
        else
        {
            inputs.Add(Key(VirtualKeys.LControl, up: false));
            inputs.Add(Key(VirtualKeys.V, up: false));
            inputs.Add(Key(VirtualKeys.V, up: true));
            inputs.Add(Key(VirtualKeys.LControl, up: true));
        }

        Send(inputs);
    }

    /// <summary>
    /// Logically releases modifier keys the user is still holding (e.g. Shift used to type "?" or ":", or AltGr) so
    /// they don't combine with injected keys. Afterwards every modifier the user still holds is pressed again; Alt and
    /// Win are followed by a mask key so the application doesn't open its menu or the Start menu.
    /// </summary>
    public static IDisposable ReleaseHeldModifiers(Func<int, bool> isUserDown)
    {
        int[] candidates = [VirtualKeys.LShift, VirtualKeys.RShift, VirtualKeys.LControl, VirtualKeys.RControl, VirtualKeys.LMenu, VirtualKeys.RMenu, VirtualKeys.LWin, VirtualKeys.RWin];
        var released = candidates.Where(vk => (GetAsyncKeyState(vk) & 0x8000) != 0).ToList();
        if (released.Count == 0)
        {
            return EmptyScope.Instance;
        }

        var inputs = new List<INPUT>();
        if (released.Any(IsAltOrWin))
        {
            // Without an intervening key, releasing Alt or Win activates the menu bar or Start menu.
            AddKeyPress(inputs, VirtualKeys.MenuMask);
        }

        foreach (var vk in released)
        {
            inputs.Add(Key(vk, up: true));
        }

        Send(inputs);
        return new RestoreScope(released, isUserDown);
    }

    private static bool IsAltOrWin(int vk) => vk is VirtualKeys.LMenu or VirtualKeys.RMenu or VirtualKeys.LWin or VirtualKeys.RWin;

    private static IEnumerable<string> EnumerateTextElements(string text)
    {
        var enumerator = System.Globalization.StringInfo.GetTextElementEnumerator(text);
        while (enumerator.MoveNext())
        {
            yield return enumerator.GetTextElement();
        }
    }

    private sealed class EmptyScope : IDisposable
    {
        public static readonly EmptyScope Instance = new();

        public void Dispose()
        {
        }
    }

    private sealed class RestoreScope(List<int> released, Func<int, bool> isUserDown) : IDisposable
    {
        public void Dispose()
        {
            var stillHeld = released.Where(isUserDown).ToList();
            if (stillHeld.Count == 0)
            {
                return;
            }

            var inputs = new List<INPUT>();
            foreach (var vk in stillHeld)
            {
                inputs.Add(Key(vk, up: false));
            }

            if (stillHeld.Any(IsAltOrWin))
            {
                AddKeyPress(inputs, VirtualKeys.MenuMask);
            }

            Send(inputs);
        }
    }
}
